export const GET_USER_EDIT_DATA = 'GET_USER_EDIT_DATA';
export const GET_USER_EDIT_PARENT_STUDENTS = 'GET_USER_EDIT_PARENT_STUDENTS';
export const GET_USER_EDIT_PARENT_STUDENTS_PHOTO = 'GET_USER_EDIT_PARENT_STUDENTS_PHOTO';
export const GET_USER_EDIT_PARENT_STUDENTS_ADD = 'GET_USER_EDIT_PARENT_STUDENTS_ADD';
export const GET_USER_EDIT_PARENT_STUDENTS_REMOVE = 'GET_USER_EDIT_PARENT_STUDENTS_REMOVE';
export const GET_USER_EDIT_STUDENT_DATA = 'GET_USER_EDIT_STUDENT_DATA';
export const GET_USER_EDIT_STUDENT_PARENT = 'GET_USER_EDIT_STUDENT_PARENT';
export const GET_USER_EDIT_TEACHER_DISCIPLINES = 'GET_USER_EDIT_TEACHER_DISCIPLINES';

export const REMOVE_USER_EDIT_DATA = 'REMOVE_USER_EDIT_DATA';

export const TOKEN = 'TOKEN';

export const IS_MOBILE = 'IS_MOBILE';

export const CONNECTED = 'CONNECTED';
export const DISCONNECT = 'DISCONNECT';

export const SET_STORAGE = 'SET_STORAGE';
export const GET_STORAGE_SERVERS = 'GET_STORAGE_SERVERS';
export const GET_STORAGE_ALIVE = 'GET_STORAGE_ALIVE';
export const ADD_STORAGE_SERVER = 'ADD_STORAGE_SERVER';
export const REMOVE_STORAGE_SERVER = 'REMOVE_STORAGE_SERVER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const RESET_ERROR = 'RESET_ERROR';
export const RESET_LOADING = 'RESET_LOADING';
export const RESET_GET_SUCCESS = 'RESET_GET_SUCCESS';
export const RESET_POST_SUCCESS = 'RESET_POST_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const GET_ABSENCES = 'GET_ABSENCES';
export const GET_ABSENCES_COMPLETE = 'GET_ABSENCES_COMPLETE';
export const SEND_MARK_ABSENCE = 'SEND_MARK_ABSENCE';
export const ABSENCE_ERROR = 'ABSENCE_ERROR';
export const JUSTIFY_ABSENCE = 'JUSTIFY_ABSENCE';
export const MARKED_ABSENCE = 'MARKED_ABSENCE';
export const REMOVED_ABSENCE = 'REMOVED_ABSENCE';
export const RECUPERATE_ABSENCE = 'RECUPERATE_ABSENCE';
export const READ_MARKED_ABSENCE = 'READ_MARKED_ABSENCE';
export const GET_CLASS_ABSENCES = 'GET_CLASS_ABSENCES';
export const GET_ABSENCE_TYPES = 'GET_ABSENCE_TYPES';

export const GET_TESTS = 'GET_TESTS';
export const MARK_TEST = 'MARK_TEST';
export const MARK_TEST_READ = 'MARK_TEST_READ';
export const REMOVE_TEST = 'REMOVE_TEST';
export const REMOVE_TEST_READ = 'REMOVE_TEST_READ';
export const TEST_ERROR = 'TEST_ERROR';
export const TEST_NOT_FOUND = 'TEST_NOT_FOUND';

export const GET_CLASSES = 'GET_CLASSES';
export const CLASSES_ERROR = 'CLASSES_ERROR';
export const ADD_CLASS = 'ADD_CLASS';
export const REMOVE_CLASS = 'REMOVE_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const GET_STUDENT_CLASS = 'GET_STUDENT_CLASS';
export const REMOVE_STUDENT_FROM_CLASS = 'REMOVE_STUDENT_FROM_CLASS';
export const ADD_STUDENT_TO_CLASS = 'ADD_STUDENT_TO_CLASS';

export const REMOVE_DISCIPLINE_TEACHER = 'REMOVE_DISCIPLINE_TEACHER';
export const NEW_DISCIPLINE_TEACHER = 'NEW_DISCIPLINE_TEACHER';
export const GET_DISCIPLINES = 'GET_DISCIPLINES';
export const ADD_DISCIPLINE = 'ADD_DISCIPLINE';
export const UPDATE_DISCIPLINE = 'UPDATE_DISCIPLINE';
export const GET_TEACHER_DISCIPLINES = 'GET_TEACHER_DISCIPLINES';
export const GET_CLASS_DISCIPLINES = 'GET_CLASS_DISCIPLINES';

export const NEW_LESSON = 'NEW_LESSON';
export const GET_LESSONS = 'GET_LESSONS';
export const GET_LESSONS_COMPLETE = 'GET_LESSONS_COMPLETE';
export const NEW_LESSON_COMPLETE = 'NEW_LESSON_COMPLETE';
export const LESSON_SUMMARY_UPDATED = 'LESSON_SUMMARY_UPDATED';
export const LESSON_SUMMARY_UPDATE = 'LESSON_SUMMARY_UPDATE';

export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENT_PHOTO = 'GET_STUDENT_PHOTO';
export const GET_STUDENTS_COMPLETE = 'GET_STUDENTS_COMPLETE';
export const GET_STUDENTS_WITHOUT_PARENT = 'GET_STUDENTS_WITHOUT_PARENT';
export const ADD_STUDENTS_WITHOUT_PARENT = 'ADD_STUDENTS_WITHOUT_PARENT';
export const REMOVE_STUDENTS_WITHOUT_PARENT = 'REMOVE_STUDENTS_WITHOUT_PARENT';

export const UPDATE_THEME = 'UPDATE_THEME';

export const GET_MODULES_GRADE = 'GET_MODULES_GRADE';
export const UPDATE_MODULES_GRADE = 'UPDATE_MODULES_GRADE';
export const GET_MODULES = 'GET_MODULES';
export const NEW_MODULE = 'NEW_MODULE';
export const UPDATE_MODULE = 'UPDATE_MODULE';

export const GET_GRADES = 'GET_GRADES';

export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_DAYS = 'GET_DAYS';
export const GET_HOURS = 'GET_HOURS';

export const GET_SELF_PHOTO = 'GET_SELF_PHOTO';
export const GET_USER_PHOTO = 'GET_USER_PHOTO';
export const GET_USER_FILES = 'GET_USER_FILES';
export const DELETE_USER_FILE = 'DELETE_USER_FILE';
export const ADD_USER_FILE = 'ADD_USER_FILE';

export const GET_TEST_GRADES = 'GET_TEST_GRADES';
export const UPDATE_TEST_GRADES = 'UPDATE_TEST_GRADES';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const GET_HOMEWORK = 'GET_HOMEWORK';
export const MARK_HOMEWORK = 'MARK_HOMEWORK';

export const GET_PARENT_STUDENT = 'GET_PARENT_STUDENT';

export const GET_COURSES = 'GET_COURSES';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const ADD_COURSE = 'ADD_COURSE';

export const GET_TEACHER = 'GET_TEACHER';
export const GET_FREE_TEACHERS = 'GET_FREE_TEACHERS';
export const GET_DIRECTOR_TEACHERS = 'GET_DIRECTOR_TEACHERS';
export const SET_DIRECTOR_TEACHER = 'SET_DIRECTOR_TEACHER';
export const SET_FREE_TEACHER = 'SET_FREE_TEACHER';

export const GET_ROLES = 'GET_ROLES';

export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';